### ISSUE TITLE
Select2 is not being rendered

### ISSUE THREAD

**Issue by amserra** [asyncee/django-easy-select2#107]
Hi. I installed the latest version of django-easy-select2 with pip on Django 4.0.3. When I use it on a model form like below, nothing happens, although the element is rendered to the HTML (image).

```python
class MyForm(forms.ModelForm):
    myfield = forms.ModelMultipleChoiceField(widget=Select2Multiple(select2attrs={'width': 'auto'})
```

![image](https://user-images.githubusercontent.com/45828914/161597769-faf1b9de-df11-4e85-ba31-a3bde8fbdc61.png)

Any fix on this?

**Comment by helixaros** [comment]
was this fixed? i have the exact same issue

**Comment by amserra** [comment]
No, I ended up using another option, [TomSelect](https://tom-select.js.org/). Did something like this in the HTML:

```html
<select name="{{ widget.name }}" autocomplete="on" {% include "django/forms/widgets/attrs.html" %}>
{% for group_name, group_choices, group_index in widget.optgroups %}{% if group_name %}
  <optgroup label="{{ group_name }}">{% endif %}{% for option in group_choices %}
  {% include option.template_name with widget=option %}{% endfor %}{% if group_name %}
  </optgroup>{% endif %}{% endfor %}
</select>

<script>
    new TomSelect("#{{ widget.attrs.id }}", {
     plugins: ['checkbox_options']
    });
</script>
```

**Comment by hartwork** [comment]
@helixaros have you compared your code to the examples in here? Are the examples working for you in practice? How would someone best reproduce the issue you have?
