### ISSUE TITLE
Ignored in production

### ISSUE THREAD

**Issue by LucasRoesler** [asyncee/django-easy-select2#16]
I installed easy-select2 following the instructions in the doc and it works perfectly in my local environment.  However, in production it seems to be completely ignored. Is there any reason why it would default back to the standard select widget?

**Comment by kevin-brown** [comment]
An easy guess would be that the static files are not being served correctly.

Are you getting any errors in the console at all in production?

**Comment by asyncee** [comment]
Hello, please try running "collectstatic" management command or copy static files manually.

**Comment by LucasRoesler** [comment]
I am serving the files out of S3 with cloudfront, I was able to verify that the files are in place, but the admin page doesn't even try to load them.  There are no 403 errors in the network log.

**Comment by asyncee** [comment]
Can you post your admin / form code please?

And check if browser console shows any errors?

 Also, if the form configured correctly, select widget should have a 'script' tag appended to it with some select2 init code (you can check it with developer tools).

**Comment by LucasRoesler** [comment]
My admin looks like

```python
class AdminProfileAdmin(admin.ModelAdmin):
    search_fields = ('user__email',)
    formfield_overrides = {
        models.ForeignKey: {'widget': apply_select2(forms.Select)},
        models.OneToOneField: {'widget': apply_select2(forms.Select)},
    }
    fieldsets = (
        ('Personal info', {
            'fields': ('user', 'title', 'status', 'organization', 'role',
                       'primary_phone', 'secondary_phone', )}),
        ('Permissions', {'fields': (
            'can_view_settings', 'can_view_billing', 'can_view_users', )}),
    )
```

The browser console shows no errors and the page DOM does not have anything related to select2 in it.

**Comment by asyncee** [comment]
Looks sane, but i have found a ticket that may be related: https://code.djangoproject.com/ticket/19303
I have no pc on my hand right now, so can not setup a test project for your case.
I think you should to try to avoid using formfield_overrides, but custom form (you can override widgets in its __init__) to see if it is working solution.

**Comment by LucasRoesler** [comment]
Sorry for the long time before my response. 

I just recently did another deploy, but not including any changes to that admin page, and now it seems to work.  I am not sure what the difference is this time. Perhaps I was mistaken about the code making it into the previous deployment.  

So, this appears to be a non-issue.  Sorry for the false alarm.
