### ISSUE TITLE
large data in django easy_select2 make it slowly

### ISSUE THREAD

**Issue by tarek-aec** [asyncee/django-easy-select2#17]
I have about 1500,340 user on my website and when I click to select one user in admin it take long time to load the large username in admin page, anyone has idea to solve the problem?

**Comment by asyncee** [comment]
I prefer to use raw_id_fields in case of django admin.

**Comment by asyncee** [comment]
Looks like there are no other ideas how to handle 1500340 users in django admin select input, except for using `raw_id_fields` and (maybe) select2 ability to load data by using ajax.

So, i'm closing it.

**Comment by tarek-aec** [comment]
thank you
