### ISSUE TITLE
Select2 4.0.0

### ISSUE THREAD

**Issue by kevin-brown** [asyncee/django-easy-select2#18]
Just a heads up, we [released Select2 4.0.0](https://select2.github.io/announcements-4.0.html) last Sunday (about a week ago). It doesn't look like it would be _too difficult_ to upgrade this project to support it as there isn't a lot of magic involved here.

**Comment by asyncee** [comment]
Hello and thank you for information, i will upgrade a project with new Select2 version.

I did not read release notes and upgrade guide yet, so just a question - does Select2 4.0.0 expects to find window.$ (jQuery) by default or it is possible to configure widget to use custom jQuery namespace?

https://github.com/asyncee/django-easy-select2/blob/master/easy_select2/static/easy_select2/js/easy_select2.js

**Comment by kevin-brown** [comment]
Select2 4.0.0 is designed to work with `jQuery.noConflict` insofar as it looks for `window.jQuery` instead of `window.$`. It's difficult to automatically pick up `jQuery.noConflict(true)` as there are no traces of where `jQuery` was assigned to, so we don't directly support that.

**Comment by asyncee** [comment]
For now new feature with Select2 4.0.0 is available https://github.com/asyncee/django-easy-select2/tree/feature/select2-4

Though, there is a release blocker: when you create related object using a green plus sign (new window opens), widget is not re-rendered with new value.

**Comment by kevin-brown** [comment]
> Though, there is a release blocker: when you create related object using a green plus sign (new window opens), widget is not re-rendered with new value.

I'm not entirely sure how this worked before, or what was changed that may have broken it.

**Comment by asyncee** [comment]
New release: 1.3 with Select 2 4.0.0. Thank you for support. Closing.
