### ISSUE TITLE
How to handle the conflict in form?

### ISSUE THREAD

**Issue by shnode** [asyncee/django-easy-select2#19]
`easy-select2` is smart.

 but as we declare the form in admin, it influence those form auto-generated by models like `markdown field`(comes from [django_markdown](https://github.com/klen/django_markdown))
which gave me js fault like:

![image](https://cloud.githubusercontent.com/assets/7784713/7625901/d0a7f094-fa30-11e4-827f-de5f976ab849.png)

so , how could I deal with multiple things in form?

**Comment by asyncee** [comment]
It looks like javascript library `jquery.markitup.js` is not loaded. This can happen if form media was overriden, or easy-select2's javascript libraries somehow conflict with ``markdown field``. Can you please show your form code and section in your admin page source code, where javascript libraries are loaded (the place in resulting html where form.media is rendered).

**Comment by shnode** [comment]
`jquery.markitup.js` has been loaded before `easy_select2`,
![image](https://cloud.githubusercontent.com/assets/7784713/7629294/ff412e34-fa5d-11e4-8127-d23069119bbc.png)

after finding so many module, `easy_select2` is the nearest I want.
`django-ajax-selects` needs to inherit from its own `AdminModel`, but I use `nested_inline`.
`django-select2` seems does not work for grappelli.
`grappelli-filter` only works for `change_list` page.
`grappelli's protosomatic raw_in_fields` does not support inline at all.

**Comment by flex1988** [comment]
el is native, markitup is a jquery function,u nid to convert it to a jquery object first.
$(el).markitup();

**Comment by jungornti** [comment]
Documentation says:

SELECT2_USE_BUNDLED_JQUERY - default is True. Set to False if your already have included custom jQuery.

This configuration option should remove jquery.min.js from list of libraries. Can you try that?

**Comment by shnode** [comment]
@jungornti  Thanks a million, I appreciate your help.
