### ISSUE TITLE
Adding Mood in Sample App broken

### ISSUE THREAD

**Issue by mknecht** [asyncee/django-easy-select2#20]
Hey,

I started the demo app according to the [guidelines](http://django-easy-select2.readthedocs.org/en/latest/sampleproject.html) and wanted to test the addition of Moods. Did not work: Entering texts, adn pressing RET did nothing. Saving did not help either. Am I doing sth wrong, or is it broken?

``` 
$ pip freeze
Django==1.7
argparse==1.2.1
-e git+https://github.com/asyncee/django-easy-select2.git@9472163506cd906a7a2219099f45473f41f902a5#egg=django_easy_select2-origin/develop
wsgiref==0.1.2
```
![selection_212](https://cloud.githubusercontent.com/assets/77181/7626960/bb312e48-fa43-11e4-8dca-fa303523e96b.png)

Cheers,
murat

**Comment by jungornti** [comment]
Well, looks like this is regression due to Select2 update or something. It is broken now. Anyway, this feature will be removed when django-easy-select2 will be updated to use Select2 4.0.0.

**Comment by mknecht** [comment]
l0l, okay. Does 4.0 not support that anymore? It's a handy feature, no?

**Comment by jungornti** [comment]
I'm not sure, but looks like 4.0 does not support that. Anyway, using Select2 in that way looks like "hack" for me, because Select2 based on ``select`` input mechanics, not text-input.

**Comment by mknecht** [comment]
okay :) thanks, closing!
