### ISSUE TITLE
It's two slow when use the select box.

### ISSUE THREAD

**Issue by shnode** [asyncee/django-easy-select2#21]
I have more than 10,000 rows in current table to be select.

how to deal with this problem

**Comment by asyncee** [comment]
In such situtation you should use Select2 + ajax. Django-easy-select2 does not support loading ajax choices out of a box, but you can read discussion https://github.com/asyncee/django-easy-select2/issues/3

Also this documentation can help you: http://select2.github.io/select2/#ajax

If you have ideas how to better integrate ajax-loading feature and django-easy-select2, please, write me.

**Comment by shnode** [comment]
Thank you, Finally we quit using django-admin.

**Comment by vigo** [comment]
Let's implement ajax load!
