### ISSUE TITLE
Use with django-storage.

### ISSUE THREAD

**Issue by martolini** [asyncee/django-easy-select2#23]
Change
`from django.templatetags.static import static`
to
`from django.contrib.staticfiles.storage import staticfiles_storage as static`
in order for this to work with other static storages.

**Comment by jungornti** [comment]
Thank you for bug report. It will be fixed as soon as possible. Also, PR is welcomed :)

**Comment by asyncee** [comment]
Fixed in release 1.3.1. Thank you.
