### ISSUE TITLE
This app is not listed on djangopackages yet

### ISSUE THREAD

**Issue by guettli** [asyncee/django-easy-select2#27]
Your app is not listed on this site yet:

https://www.djangopackages.com/grids/g/auto-complete/

Would be nice if it would.

**Comment by asyncee** [comment]
Hello, Thomas, thank you for information! It is actually listed in widgets
grid, but i will add it to an auto-complete too.

You can check it here:

https://www.djangopackages.com/packages/p/django-easy-select2/

**Comment by asyncee** [comment]
Added application to the grid, no check boxes yet, need to wait until grid cache expires.

**Comment by guettli** [comment]
I can see the app in the grid. Thank you.
