### ISSUE TITLE
widgets won't render and I don't know why

### ISSUE THREAD

**Issue by randomshinichi** [asyncee/django-easy-select2#28]
I have code like this:
```python
from django import forms
from django_countries.fields import LazyTypedChoiceField, countries
from easy_select2.widgets import Select2Multiple

class LeadForm(forms.Form):
    overseas_company = forms.MultipleChoiceField(
        choices=countries,
        label='Do you have any companies overseas and where?',
        widget=Select2Multiple
    )
```
But it always renders like a normal `forms.SelectMultiple`. Your documentation doesn't really cover this case specifically, and I have no idea where to start troubleshooting. Any ideas? I even changed the import to `easy_select2.widgets` specifically.

**Comment by asyncee** [comment]
Hello!

First of all, let's check if form media was rendered properly. You should see select2 javascript libary in the page source code. More about media [in the docs](https://docs.djangoproject.com/en/1.9/topics/forms/media/).

Secondly, try to pass **instance** of `Select2Multiple` instead of class.

Also you should check if there any javascript errors in browser console, which may prevent widget loading.

**Comment by randomshinichi** [comment]
I tried passing an instance but it didn't make a difference.

There is no reference to the select2 javascript library in the page source code. No js file is being loaded from Django. Is this intended behaviour? Am I supposed to setup Form Assets myself? I thought including the Select2Multiple() widget would cause the required JS files to be loaded, since this was not mentioned in the documentation.

**Comment by asyncee** [comment]
No. Django can handle form assets by itself:

> Regardless of whether you define a media declaration, all Form objects have a media property. The default value for this property is the result of adding the media definitions for all widgets that are part of the form

That means dependent static files will be loaded automatically.

So it looks like you are missing ``{{ form.media }}`` in the page source. Try to add it to the ``<head>`` section of your page.

**Comment by randomshinichi** [comment]
Oh yes, it works now!

Good practice question: is it good to add `{{ forms.media }}` to base.html (because that contains the `<head>` section)? Then it will be run for every page, even the ones that don't have a form or use the Select2 widget.

Right now my base.html has this snippet in `<head>`:

```
    {% if form.media %}
      {{ form.media }}
    {% endif %}
```

**Comment by asyncee** [comment]
As a good practice advice you can use this:

1. in base.html you create a block, for example `{% block extrahead %}{% endblock %}`.
2. override this block on every single page, where you need custom js, css, form or widget media, etc, like this:

```
{% block extrahead %}
    {{ form.media }}
{% endblock %}
```

This way you can work with pages, that have multiple forms, following DRY principle.

I think we can close it now.
