### ISSUE TITLE
Feature Request: Use AJAX to connect to large datasets?

### ISSUE THREAD

**Issue by mkoistinen** [asyncee/django-easy-select2#3]

**Comment by sebastien247** [comment]
:+1:

**Comment by asyncee** [comment]
For me, django-easy-select2 is lightweight wrapper on select2 library, which provides easy-to-use basic select2 functionality in a django project.
If you need feature-rich solution, i recoomend you to look at the latest ``django-select2`` library, which have ajax loading support.

Anyway, if anyone **really** want this functionality in ``django-easy-select2``, please feel free to contribute.
