### ISSUE TITLE
Select depend on other field

### ISSUE THREAD

**Issue by iho** [asyncee/django-easy-select2#30]
Hi 

How to filter field list depending on  value of other field?

**Comment by asyncee** [comment]
Hi, django easy select2 does not have this feature, but you can try django smart selects, or write it yourself.

**Comment by iho** [comment]
> django smart selects
Does it have autocomplete function?

**Comment by iho** [comment]
Please close it. I already implement what I need with django-easy-select2 and few json views.

**Comment by asyncee** [comment]
Glad you got it working.

**Comment by MahendraNG** [comment]
@iho Can you post your solution here?
