### ISSUE TITLE
Easy Select2 does not work with 1.11

### ISSUE THREAD

**Issue by jayanthbagare** [asyncee/django-easy-select2#33]
Hi, 
Easy Select 2 does not seem to be working with 1.11(the latest release). The last known release to work on is 1.10.7 

Attached is the screenshot of the error.

<img width="1432" alt="screen shot 2017-04-17 at 2 47 03 pm" src="https://cloud.githubusercontent.com/assets/290588/25084892/c8ff6b34-237c-11e7-827b-953ee3c4ce3d.png">

**Comment by asyncee** [comment]
Hello, thank you for report. Can you show the code and describe how to reproduce this bug?

**Comment by jayanthbagare** [comment]
Hi,
Below is the code. Hope this helps.



admin.py
=======
RelationshipForm = select2_modelform(Relationship)
ReportForm = select2_modelform(Report)

class RelationshipAdmin(admin.TabularInline):
    model = Relationship
    fk_name = 'bp_predicate'
    exclude = ['createdBy']
    form = RelationshipForm

    def formfield_for_foreignkey(self, db_field, request, **kwargs):
        logger.debug('Field ' + str(db_field.name))
        if db_field.name != "bp_predicate":
            kwargs["queryset"] = BusinessPartner.objects.filter(createdBy=request.user)
            return super().formfield_for_foreignkey(db_field, request, **kwargs)


models.py
=======
class Relationship(models.Model):
    bp_subject = models.ForeignKey(BusinessPartner,related_name='subject',blank=True)
    bp_predicate = models.ForeignKey(BusinessPartner,related_name='predicate',blank=True)
    relationship = models.CharField(max_length=2,blank=True,choices=(('po','parent_of'),
                                             ('co','child_of'),('so','spouse_of')))
    createdBy = models.ForeignKey('auth.User',blank=True,null=True)

**Comment by asyncee** [comment]
Thank you, i'll look into this problem asap.

For now you can try to use alternative for select2_modelform, for example, select2_modelform_meta or specify select2 fields by hand.

**Comment by asyncee** [comment]
Released 1.3.4 with django 1.11 support. If issue remains, feel free to reopen. Thank you.

**Comment by jayanthbagare** [comment]
Awesome thanks, will check it out.
