### ISSUE TITLE
Sample project does not work?

### ISSUE THREAD

**Issue by gamesbook** [asyncee/django-easy-select2#34]
After I run `python manage.py migrate` (the docs still say syncdb), then I use:
```
python manage.py runserver 
```
But no admin is available and the project does not show up on the root either?

**Comment by asyncee** [comment]
Well, it seems something went wrong. I can not say what exactly - we need more details.

Also, tests are running okay in test environment (sampleproject demoapp), so be sure to check out tox.ini (project directory and settings).

**Comment by gamesbook** [comment]
Sorry, have moved on from this.  Maybe you can try and duplicate the problem in a clean environment?  If I really need to use this tool in future I will try it again.

**Comment by asyncee** [comment]
Okay, good luck ;)

**Comment by gamesbook** [comment]
@asyncee I don't understand, but OK, its your project!

**Comment by asyncee** [comment]
Sorry, there are a little misunderstanding. I have no spare time to work on this project for now and without any attached logs, or images, or some other debug information i can not make an assumption what is actually wrong.

I'm sure, that the widget should be working - yes, sampleproject is maybe, stale, but standalone installation should be working.

Just use `pip install` on a working project.

**Comment by gamesbook** [comment]
Outputs:
```
$./manage.py syncdb
Unknown command: 'syncdb'
Type 'manage.py help' for usage.
```
```
$./manage.py migrate
Operations to perform:
  Apply all migrations: admin, auth, contenttypes, demoapp, sessions
Running migrations:
  No migrations to apply.
```
```
$./manage.py makemigrations admin, auth, contenttypes, demoapp, sessions
App 'contenttypes,' could not be found. Is it in INSTALLED_APPS?
App 'admin,' could not be found. Is it in INSTALLED_APPS?
App 'demoapp,' could not be found. Is it in INSTALLED_APPS?
App 'auth,' could not be found. Is it in INSTALLED_APPS?
```

```
$./manage.py runserver
Performing system checks...

System check identified no issues (0 silenced).
July 04, 2017 - 13:59:15
Django version 1.11.2, using settings 'sampleproject.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
[04/Jul/2017 13:59:27] "GET / HTTP/1.1" 404 930
```
In the browser:
```
Page not found (404)
Request Method:	GET
Request URL:	http://127.0.0.1:8000/
Using the URLconf defined in sampleproject.urls, Django tried these URL patterns, in this order:
^admin/
^static\/(?P<path>.*)$
The empty path didn't match any of these.
You're seeing this error because you have DEBUG = True in your Django settings file. Change that to False, and Django will display a standard 404 page.
```

**Comment by asyncee** [comment]
I checked this in clear environment with `django==1.8` and it worked fine.

Please try this:

1. bash bootstrap.sh - this will deploy project
2. source env/bin/activate - activate virtualenv
3. pip install django==1.8
4. ./manage.py migrate
5. ./manage.py runserver

Actually, sampleproject is a little outdated (django 1.9 and later needs different templates configuration, etc).

**Comment by gamesbook** [comment]
I found there was no user available to log in to the admin site, so I had to create one.  Shall I submit a pull request with updated instructions?

**Comment by asyncee** [comment]
Sure, thank you!
For now, as this project is stable, i'm almost not working with sampleproject. If you want to improve it, pull requests are welcomed :)

Also, soon i will search for a project maintainer.
