### ISSUE TITLE
Related model combobox doesn't update after add in Django 2

### ISSUE THREAD

**Issue by md1023** [asyncee/django-easy-select2#38]
1) cloned demoapp, `pip install -U django`
2) setup demoapp, updated config and migrations to run under Django2
3) run demo, logged in
4) try to add new note - press plus; type in `max` into inputs, click save
5) I've been returned to add note page but user combo still shows dashes `---------`
6) click on dropdown box and see there new option `max`
7) click save note and note is saved with user `max`

I guess some problem in `trigger('change')`. In my django2 app I had to write `window.$('select').trigger('change')` instead of `$('select').trigger('change')`.

**Comment by asyncee** [comment]
Currently, i can not investigate this due to missing free time.

Can you check if `$` and `window.$` are different objects?

Jquery must expose itself to the window scope by default.

**Comment by md1023** [comment]
```
>> $ == window.$
false
>> $
function jQuery(selector, context)
>> window.$
function n(a, b)
```
First function leads to jquery.js and `n(a, b)` is a function from `jquery.min.js`.

**Comment by asyncee** [comment]
It would be great if you can submit a pull request.

Thanks!

**Comment by asyncee** [comment]
@gauravv7 any comments on this? Can you test if the bug exists?
