### ISSUE TITLE
question: ArrayField support

### ISSUE THREAD

**Issue by nskalis** [asyncee/django-easy-select2#39]
Hi,

Not sure if I am asking the right thing here, but could you please share an example
of saving a `list` coming from `django-easy-select2` in PostgreSQL `array` field ?

In other words, is Django `ArrayField` supported ?

**Comment by asyncee** [comment]
Hey, there are `Select2Multiple` widget that you can try.

In fact, it just a mixin to SelectMultiple, so you it should work out of the box.

```
class Select2Multiple(Select2Mixin, forms.SelectMultiple):
    """Implement multiple select widget with Select2."""
    pass
```

I can not give you working code, because i do not use django at the moment, but is should give you an idea:

```
if form.is_valid():
    lst = form.cleaned_data['you_field_name']
   # somehow transform SelectMultiple data into list object
    mymodel.array_data = lst
    mymodel.save()
```

**Comment by nskalis** [comment]
thanks a lot!
