### ISSUE TITLE
Doesn't work for dynamically added forms in inline admins

### ISSUE THREAD

**Issue by Tyilo** [asyncee/django-easy-select2#45]
At least for TabularInline

**Comment by RyanStack** [comment]
I would also like to use django-easy-select2 for StackedInline.  Any idea on the eta for this feature?

**Comment by gauravv7** [comment]
@RyanStack it would be released shorty in a few days. Some tests are being done.
I ll update you with some quick fix if its gonna take time.

**Comment by RyanStack** [comment]
@gauravv7 Great to hear!

**Comment by gauravv7** [comment]
@RyanStack @Tyilo This issue is resolved completely with the release of version 1.5.2. Please let us know in case of any issues.
I hope we helped.
