### ISSUE TITLE
autocomplete_fields inputs initialised twice

### ISSUE THREAD

**Issue by leibowitz** [asyncee/django-easy-select2#56]
Note that I'm using `SELECT2_USE_BUNDLED_JQUERY = False`. So I am using the bundled django jquery (e.g. in the admin)

~~Since the last change introduced in https://github.com/asyncee/django-easy-select2/pull/55, any `autocomplete_fields` (django 2+) are now initialised twice.~~

~~Not sure why, but removing [these lines](https://github.com/asyncee/django-easy-select2/blob/186587e095078fa337214635bfa82e99ac6589e9/easy_select2/static/easy_select2/js/easy_select2.js#L3-L11) seems to solve my issue - could this be a solution that works for everyone?~~
Update: scrap all that, still trying to figure out what is the cause... will update soon

I believe the issue is with the new `django-autocomplete-light` rather (using both, so hard to tell). I will close until I know for sure and will re-open/recreate a new ticket if I find it's `django-easy-select2`

**Comment by asyncee** [comment]
Great, thank you!
