### ISSUE TITLE
Using tinyMCE reloads jQuery namespace, select2 registers in the new jQuery namespace

### ISSUE THREAD

**Issue by jaikanthjay46** [asyncee/django-easy-select2#57]
I have this weird script order, jquery loads , jquery-ui registers itself, jquery.init.js where jQuery name space is cleared and moved to django.jQuery.

- Now, easy-select2  loads, no jQuery so fills it with django.jQuery and stored $ and _djq, both pointing to django.jQuery and remains that way due to closure.
- Next tinymce's jQuery loads replaces jQuery namespace.
- Next select2 load and register to the newly created jQuery namespace.
- easy-select js nows tries to call select2 since it remembers only django.jQuery instance (due to closure) a error is thrown stating there is no function select2

```
<script type="text/javascript" src="/admin/jsi18n/"></script>
<link href="/static/tabbed_admin/css/jquery-ui-1.11.4.min.css" type="text/css" media="all" rel="stylesheet">
<link href="/static/tabbed_admin/css/tabbed_admin.css" type="text/css" media="all" rel="stylesheet">
<link href="/static/easy_select2/vendor/select2/css/select2.min.css" type="text/css" media="screen" rel="stylesheet">
<link href="/static/easy_select2/css/easy_select2.css" type="text/css" media="screen" rel="stylesheet">
<script type="text/javascript" src="/static/admin/js/vendor/jquery/jquery.js"></script>
<script type="text/javascript" src="/static/tabbed_admin/js/jquery-ui-1.11.4.min.js"></script>
<script type="text/javascript" src="/static/easy_select2/js/init.js"></script>
<script type="text/javascript" src="/static/admin/js/jquery.init.js"></script>
<script type="text/javascript" src="/static/easy_select2/js/easy_select2.js"></script>
<script type="text/javascript" src="/static/django_tinymce/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/static/admin/js/core.js"></script>
<script type="text/javascript" src="/static/easy_select2/vendor/select2/js/select2.min.js"></script>
<script type="text/javascript" src="/static/django_tinymce/init_tinymce.js"></script>
<script type="text/javascript" src="/static/admin/js/admin/RelatedObjectLookups.js"></script>
<script type="text/javascript" src="/static/admin/js/actions.js"></script>
<script type="text/javascript" src="/static/admin/js/urlify.js"></script>
<script type="text/javascript" src="/static/admin/js/prepopulate.js"></script>
<script type="text/javascript" src="/static/admin/js/vendor/xregexp/xregexp.js"></script>

```

**Comment by asyncee** [comment]
Hello and thank you for bug report!

Sadly, i do not use django for a few years now, so this library is mainained by @gauravv7 and community.

Feel free to submit a PR :)

**Comment by jaikanthjay46** [comment]
Thanks for taking notice, I wish there were more elegant ways to solve this @gauravv7, hit me up if you have some.

**Comment by gauravv7** [comment]
@jaikanthjay46 all we want is to capture an instance of select2 to work upon, your approach seems fine. I ll do some more testing to figure more edge cases.
basically we don't want to pick an object from unknown source, so as we get unknown behavior. JS allows us monkey-patching.
