### ISSUE TITLE
raw_id_fields not working, exclude and fields in customized form not working!

### ISSUE THREAD

**Issue by a-roomana** [asyncee/django-easy-select2#62]
hi!
i use django 2.2.5 and django-easy-select2 1.5.6
i have two problem

1. `raw_id_fields` not working by `select2_modelform`
2. `fields` or `exclude` in custome form not working by `select2_modelform`

for example:
```python
class PageUpdateAdminForm(forms.ModelForm):
	class Meta:
		model = Page
		exclude = ('site', 'type')

@admin.register(Page)
class PageAdmin(AdminViewMixin, admin.ModelAdmin):
	form = select2_modelform(Page, form_class=PageUpdateAdminForm)
	raw_id_fields = ('user',)
```

the user field is showing by select2 and the exclude fields are exists in model form

**Comment by gauravv7** [comment]
Hey @a-roomana 

Thanks for posting your query.

for the 1st, raw_id_fields is a property of ModelAdmin, not ModelForm. For such a scenario, you can either not use custom form, then raw_id_fields would work directly with ModelAdmin or you can assign a custom widget in the form you are making.  
in the below lines, I am assuming your `Page` model would be having a field `ext_user` as a foreignKey to `User` model
`    ext_user = forms.ModelChoiceField(
        User.objects.all(),
        widget=ForeignKeyRawIdWidget(Album._meta.get_field("ext_user").remote_field, admin.site)
    )`

`remote_field` is introduced in django 2.0 ([helper-link](https://github.com/oscarmlage/django-cruds-adminlte/issues/48))

for the 2nd, its a bug actually of which I am not sure yet. But a work-around is to copy excludes in the PageAdmin class as well. It works then

so the code would be like
```
class PageUpdateAdminForm(forms.ModelForm):
    ext_user = forms.ModelChoiceField(
        User.objects.all(),
        widget=ForeignKeyRawIdWidget(Album._meta.get_field("ext_user").remote_field, admin.site)
    )
    class Meta:
        model = Page
        exclude = ('site', 'type')

@admin.register(Page)
class PageAdmin(AdminViewMixin, admin.ModelAdmin):
	form = select2_modelform(Page, form_class=PageUpdateAdminForm)
	raw_id_fields = ('user',)
        **exclude = ('site', 'type')**
```

let me know if it works or not for you. Also if some problem persists, please share the code or models that you have defined.

**Comment by gauravv7** [comment]
closing this issue due to no further communication.
