### ISSUE TITLE
Git tags missing for releases 1.4.0 to 1.5.7 ?

### ISSUE THREAD

**Issue by hartwork** [asyncee/django-easy-select2#66]
Hi!

Is there a specific reason when release from 1.4.0 on do not have Git release tags in here any more? Do you have local tags that you didn't push? Would you welcome help finding the releated commits to create the missings tags?

Best, Sebastian

**Comment by asyncee** [comment]
Hi, Sebastian!

Sadly, i'm not using Django for a few years from now, so there are not much contributions from me, but most contributions come from community and @gauravv7. Currently i'm only pushing new releases to pypi, that is why there are no releases on github.

Any help is welcomed :)

Thanks!

**Comment by hartwork** [comment]
I wrote a brute-force script to find tags. Here's what it found:

```console
# time ./recover-django-easy-select2-tags.sh >/dev/null 
# 1.4.0
git tag -m '' 1.4.0 c3fb29b76019b1003f2f5eac674cae24bea96176  # option 1
git tag -m '' 1.4.0 c9253a0ebf6be4318379e5be5c16444fdff38f24  # option 2
git tag -m '' 1.4.0 da27c1c8877dc8fd544f3b3447e21fe31f4edfde  # option 3
git tag -m '' 1.4.0 3f7e8d4011ac9931e25a503802dc8c26709e9631  # option 4
git tag -m '' 1.4.0 771e2924fb39578630c9a9cabacb34d5e66b2cdf  # option 5

# 1.5.0
git tag -m '' 1.5.0 d35df37999a246b5182b355b04f40a62a26f301f  # option 1

# 1.5.1
git tag -m '' 1.5.1 1495b1f566f4bc43281bb4604be200f3d117209e  # option 1
git tag -m '' 1.5.1 4e5f46de2b0b59aad255604cc0df05b2697a221d  # option 2

# 1.5.2
git tag -m '' 1.5.2 599a3364492538570ab942417011c7ac7ff21142  # option 1
git tag -m '' 1.5.2 4c7ca93e6ea4167868b18f3f189f907be613a975  # option 2

# 1.5.3
git tag -m '' 1.5.3 0b4e84d0dea66d37f4e0f8da4a9f7283f851f44c  # option 1
git tag -m '' 1.5.3 563610873f3f53b085c5de79ee820107a507a750  # option 2

# 1.5.4
git tag -m '' 1.5.4 51214d60f8f6b212948e6a9f45cc70554d2549a7  # option 1

# 1.5.5
git tag -m '' 1.5.5 bd7c58bac4eded281ec734d5b5461d493f497f5a  # option 1
git tag -m '' 1.5.5 186587e095078fa337214635bfa82e99ac6589e9  # option 2
git tag -m '' 1.5.5 f81bbaa91d0266029be7ef6d075d85f13273e3a5  # option 3

# 1.5.6
git tag -m '' 1.5.6 369da541336c18574a93ff554d41136371b217fb  # option 1
git tag -m '' 1.5.6 33ea44a2d18efa845820101c7f4f2120c16badfd  # option 2
git tag -m '' 1.5.6 7782f891906c74f8297c9eef65eb9129ac1c79dd  # option 3
git tag -m '' 1.5.6 f337e0eee985482a687720b6df77a82427cc3485  # option 4
git tag -m '' 1.5.6 93305a4c08e0262589bcf8ffd27ee167f55a61f5  # option 5
git tag -m '' 1.5.6 1ced19c5b46fe47e1cb4f7c4ee3266c2654d4060  # option 6

# 1.5.7
git tag -m '' 1.5.7 0a87c501bc8fd7f3416efd07e72d6f50d14b235d  # option 1


real    1m16.153s  # on tmpfs
user    0m47.528s
sys     0m32.129s
```

The first option is the oldest commit to tag possible, the second option the second oldest (in topological order). Multiple options are the result of changes to files that are not contained in the tarball.

What do you think?

**Comment by hartwork** [comment]
Script `recover-django-easy-select2-tags.sh`:

```bash
#! /usr/bin/env bash
# Copyright (C) 2020 Sebastian Pipping <sebastian@pipping.org>
# Licensed under GPL v3 or later
set -e

[[ -d django-easy-select2 ]] \
        || git clone https://github.com/asyncee/django-easy-select2.git
pushd django-easy-select2
    all_revs=( $(git rev-list --all --topo-order --reverse) )
popd
for v in 1.4.0 1.5.0 1.5.1 1.5.2 1.5.3 1.5.4 1.5.5 1.5.6 1.5.7 ; do
    prefix="django-easy-select2-${v}"
    tarname="${prefix}.tar.gz"

    [[ -f "${tarname}" ]] \
            || wget "https://files.pythonhosted.org/packages/source/d/django-easy-select2/${tarname}"

    [[ -d "${prefix}" ]] \
            || git clone django-easy-select2 "${prefix}"

    echo "# ${v}" >&2
    count=0

    for r in ${all_revs[@]} ; do
        pushd "${prefix}"
            git reset --hard
            git clean -d -f
            git checkout "${r}" 2>/dev/null
        popd
        tar xf "${tarname}"
        pushd "${prefix}"
            idential=true
            git diff --quiet || idential=false
            git reset --hard
            git clean -d -f
        popd
        ${idential} && {
            count=$(( count + 1 ))
            echo "git tag -m '' ${v} ${r}  # option ${count}" >&2
        }
    done

    echo >&2
done
```

**Comment by asyncee** [comment]
Thanks a lot for your help! Now i'm thinking if pypi releases is enough, just to avoid any synchronization between github and pypi.

What do you think?

**Comment by hartwork** [comment]
> Thanks a lot for your help! Now i'm thinking if pypi releases is enough, just to avoid any synchronization between github and pypi.

I don't understand. Could you elaborate?

With the list of options for each tag above, it would take nothing more than:
- a decision if you want to go for (a) most early or (b) most recent commit or (c) case by case; if you want me to dig more into (c), can do. (a) and (b) are both cheap.
- copy-paste and run the right git tag commands
- push the tags

With the tags, things like this become possible: Using `git blame` or `git log` to find a specific commit that introduces certain behaviour and then using `git tag --contains <commitish>` to learn what commit first introduces the change to the public.

**Comment by hartwork** [comment]
I have went through the candidates case by case now and pushed the resulting tags. They can be seen on the [releases page](https://github.com/asyncee/django-easy-select2/releases) now, closing.

**Comment by asyncee** [comment]
Thanks a lot!
