### ISSUE TITLE
Drop support for Django … and Python …

### ISSUE THREAD

**Issue by hartwork** [asyncee/django-easy-select2#94]
Hi!

After PR #93 is merged, I consider making another PR dropping support for the following Django and Python versions:

- [Django](https://endoflife.date/django)
  - Django 2.0 — end-of-life already
  - Django 2.1 — end-of-life already
  - (Django 2.2 — end-of-life by 2022-05-01)
  - Django 3.0 — end-of-life already
  - Django 3.1 — end-of-life by 2022-01-01 
- [Python](https://endoflife.date/python)
  - Python 3.5 — end-of-life already
  - Python 3.6 — end-of-life by 2022-12-23
  - (Python 3.8 — no particular need, save runtime and CO2, move coverage collection to (3.7 or) 3.10)
  - (Python 3.9 — no particular need, save runtime and CO2)

The ones in braces are controversial, and I am just voicing an opinion for discussion.

After a decision, the plan for the pull request would be to:
- Introduce `python_requires` with `>=3.7` to `setup.py`.
- Introduce `install_requires` with e.g. `Django>=3.2` to `setup.py`.
- Drop things from `tox.ini`.
- Drop things from CI YAML files.

What do you think?

Best, Sebastian

CC @asyncee @gauravv7 @mikekeda

**Comment by asyncee** [comment]
Very good idea. As we are dropping support, last supported version should be stated in the docs so uses can use legacy version if they have to. I think it is better to stick to 3.7+ than 3.10 because the latter is too new yet.

**Comment by gauravv7** [comment]
Yes I also agree, we can drop for these previous versions. Lets go ahead with this.

**Comment by hartwork** [comment]
Okay good, I'll create a PR. Yes, let's keep Python 3.7 for sure.
